routes/web.php
<?php

use App\Http\Controllers\LoginController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

include('tempahan/admin.php');
include('tempahan/pengurus.php');
include('tempahan/penempah.php');

Route::get('/', function () {
    return view('welcome');
});

Route::get('/log-masuk',[LoginController::class,'login'])->name('logmasuk');
Route::post('/authenticate',[LoginController::class,'authenticate'])->name('periksa.pengguna');
Route::post('/lupa-katalaluan',[LoginController::class,'forgotPassword'])->name('lupa.katalaluan');
Route::post('/log-keluar',[LoginController::class,'logout'])->name('logkeluar');


Route::middleware('auth:sanctum')->resource('admin-user',UserController::class);

resources/views/admin/borang.blade.php
@extends('layouts.master')
@section('title', 'Borang Tambah Pengguna')
@section('content')

@if(isset($user->id))
<h3>Borang Kemaskini Pengguna</h3>
@else
<h3>Borang Tambah Pengguna</h3>
@endif

@if (session('success'))
    <div class="alert alert-success">
        {{ session('success') }}
    </div>
@endif

@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif


@if(isset($user->id))
<form action="{{route('admin-user.update',$user->id)}}" method="POST">
  @method('PUT')
@else
<form action="{{route('admin-user.store')}}" method="POST">
@endif

  @csrf
  <div class="mb-3">
    <label class="form-label">Nama Pengguna</label>
    <input type="text" name="name" value="{{old('name',$user->name)}}" class="form-control">
  </div>

  <div class="mb-3">
    <label class="form-label">Emel</label>
    <input type="email" name="email" value="{{old('email',$user->email)}}" class="form-control">
  </div>

  <div class="mb-3">
    <label class="form-label">Katalaluan</label>
    <input type="password" name="password" value="{{old('password',$user->password)}}" class="form-control">
  </div>

  <div class="mb-3">
    <label class="form-label">Pengesahan Katalaluan</label>
    <input type="password" name="password_confirmation" value="{{old('password',$user->password)}}" class="form-control">
  </div>

  <button type="submit" class="btn btn-primary">Simpan</button>
  
  @if(isset($user->id))
  <a class="btn btn-warning" href="{{route('admin-user.edit',$user->id)}}">Set Semula</a>
  @else
  <a class="btn btn-warning" href="{{route('admin-user.create')}}">Set Semula</a>
  @endif
  
  <a class="btn btn-danger" href="{{route('admin-user.index')}}">Kembali</a>
</form>
@endsection

resources/views/admin/senarai.blade.php
@extends('layouts.master')
@section('title', 'Senarai Pengguna')
@section('content')
<h1>Pentadbiran Senarai Pengguna </h1>
@if (session('success'))
    <div class="alert alert-success">
        {{ session('success') }}
    </div>
@endif
<form action="{{route('admin-user.index')}}">
    @csrf
    <div class="mb-3">
    <label class="form-label">Nama Pengguna</label>
    <input type="text" name="name" value="{{$name}}" class="form-control">
    </div>

    <button type="submit" class="btn btn-primary">Cari</button>
    <a class="btn btn-warning" href="{{route('admin-user.index')}}">Set Semula</a>
</form>

<br>
<br>

<a class="btn btn-success" href="{{route('admin-user.create')}}">Tambah</a>


<br>
<table class="table table-striped">
    <tr>
        <th>Bil</th>
        <th>Nama Pengguna</th>
        <th>Emel</th>
        <th>Tindakan</th>
    </tr>
    @php
    $i = $users->firstItem();
    @endphp
    
   @foreach($users as $item)
   <tr>
        <td>{{$i++}}</td>
        <td>{{$item->name}}</td>
        <td>{{$item->email}}</td>
        <td>

            <a class="btn btn-info" href="{{route('admin-user.edit',$item->id)}}">Kemaskini</a>

            <form action="{{route('admin-user.destroy',$item->id)}}" method="POST">
                @method('delete')
                @csrf
                <button type="submit" onclick="return confirm('Anda pasti untuk hapus?')" 
                class="btn btn-danger">Hapus</button>
            </form>
            
        </td>
    </tr>
   @endforeach
</table>
{{ $users->appends(['name'=>$name])->links() }}
@endsection